name: C++ Test with Google Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/run-cmake@v2
        with:
          cmake-version: '3.18.2'

      - name: Build with CMake
        run: |
          cmake -B build
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ./tests
